language: python

# Default linux jobs
os: linux
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/test
    - $HOME/.tox
    - $HOME/qemu

env:
  global:
    - QEMU_PREFIX=$PWD/tests
    - QEMU_FILE=.qemu.yml
    - QEMU_GROUP=wheel
    - QEMU_GID=1000
    - QEMU_UID=1000
    - DOCKER_COMPOSE_FILE='tests/.bin/docker-compose.yml'
  matrix:
    - TEST="yes" LOCAL="no"  PIP="no"  HUB="no"
    - TEST="no"  LOCAL="yes" PIP="no"  HUB="no"
    - TEST="no"  LOCAL="yes" PIP="yes" HUB="no"
    - TEST="no"  LOCAL="yes" PIP="no"  HUB="yes"


before_install:
  - if [ $TEST = "yes" ]; then \
      pip install --upgrade tox \
      && echo 'repo_token: '$COVERALLS_REPO_TOKEN > .coveralls.yml \
      && tox \
      rm .coveralls.yml; \
    fi

install:
  - if [ $LOCAL = "yes" ]; then \
      pip install .
    fi

before_script:
  - if [ $LOCAL = "yes" ]; then \
      qemu-composer --help; \
    fi

script:
  - if [ $LOCAL = "yes" ]; then \
      qemu-composer --prefix $QEMU_PREFIX \
                    --file $QEMU_FILE \
                    --group $QEMU_GROUP \
                    --gid $QEMU_GID \
                    --uid $QEMU_UID \
                    build; \
    fi

after_script:
  - if [ $LOCAL = "yes" ]; then \
      docker-compose \
        --file $DOCKER_COMPOSE_FILE \
        up \
        --build \
        -d; \
    fi
  
  
after_success:
  - if [ $PIP = "yes" ]; then \
      python setup.py register \
                      --show-response \
                      --list-classifiers \
                      --strict; \
  - if [ $PIP = "yes" ]; then \
      python setup.py sdist --show-response; \
    fi
  - if [ $PIP = "yes" ]; then \
      python setup.py upload -- show-response; \
  - if [ $HUB = "yes" ]; then \
      docker login \
        --username $HUB_USERNAME \
        --password $HUB_PWD; \
    fi
  - if [ $HUB = "yes" ]; then \
      docker-compose \
        --file $DOCKER_COMPOSE_FILE \
        push; \
    fi

# don't notify me when things fail
notifications:
  email: false

